apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mce-metrics-exporter
  labels:
    app: mce-metrics-exporter
spec:
  selector:
    matchLabels:
      app: mce-metrics-exporter
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    scheme: http