---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mce-metrics-exporter
  namespace: openshift-mce-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mce-metrics-reader
rules:
- apiGroups: ["agent-install.openshift.io"]
  resources: ["infraenvs", "agents", "agentclusterinstalls"]
  verbs: ["get", "list"]
- apiGroups: ["hive.openshift.io"]
  resources: ["clusterdeployments", "machinesets"]
  verbs: ["get", "list"]
- apiGroups: ["cluster.open-cluster-management.io"]
  resources: ["managedclusters", "managedclustersets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["namespaces", "nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mce-metrics-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mce-metrics-reader
subjects:
- kind: ServiceAccount
  name: mce-metrics-exporter
  namespace: openshift-mce-monitoring