
apiVersion: v1
kind: ConfigMap
metadata:
  name: mce-aggregator-config
  namespace: openshift-mce-monitoring
data:
  clusters.yaml: |
    # Configuration for all MCE clusters to monitor
    clusters:
      - name: mce-prod-1
        # Option 1: Specify full route URL
        route_url: https://mce-metrics-exporter-openshift-mce-monitoring.apps.mce-prod-1.example.com/metrics
        # Option 2: Just specify the domain (will build the route URL automatically)
        # domain: apps.mce-prod-1.example.com
        
      - name: mce-prod-2
        domain: apps.mce-prod-2.example.com
        
      - name: mce-dev-1
        domain: apps.mce-dev-1.example.com
        
      - name: mce-staging
        domain: apps.mce-staging.example.com
        
    # You can also specify tokens directly (not recommended for production)
    # clusters:
    #   - name: external-cluster
    #     route_url: https://external-mce.example.com/metrics
    #     token: "eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9..."

  # Aggregator settings
  collection.interval: "60"
  log.level: "INFO"